- templates/members/members_history.html
Fix broken image links at https://metalab.at/member/history/
> Fix pixel_blue.png static url in template

- members/views.py
rough cleanup of members/views.py
> Sanitise members views

- cal/migrations/0001_initial.py
- core/migrations/0001_initial.py
- members/migrations/0001_initial.py
- members/models.py
- projects/migrations/0001_initial.py
- projects/models.py
- sources/migrations/0001_initial.py
- sources/models.py
> Add django migrations

- HACKING_WITH_VAGRANT
- provision_vagrant.yml
> Feature/#70 added HACKING_WITH_VAGRANT and added loading fixtures with ansible

- members/models.py
Fix for debt calculation when a membership kind has multiple membership fee entries
> Fixed debt calculation when there is more than one MembershipFee

- static/stylesheets/layout.css
- templates/base.html
- templates/index.html
move issue tracker link to main navigation menu; 
move impressum to footer; 
add calendar to navigation menu
> change navigation items (issue tracker, imprssum, calendar)

- provision_vagrant.yml
MOS VM works now again.
running MOS on the box with python2
> fixed MOS VM (Vagrant)

- provision_vagrant.yml
- requirements-dev.txt
- requirements.txt
- static/javascripts/ml-ajaxtools.js
- templates/members/member_list.html
updated vagrant VM; removed legacy; HTML fixes
> vagrant update, removed legacy, fixes

- members/models.py
fixes Issue https://github.com/Metalab/mos/issues/88
> feat: implemented iButton Regex

- members/models.py
> fix crash when user has no payments

- members/models.py
- static/stylesheets/members.css
- templates/members/members_details.inc
Members and admins alike want to know how a member's balance came to be. This pulls back the curtain, exposing this information.
> show members their balance history

- members/admin.py
Sorte these by start date automatically instead of by added date:
> sort membership fees by date in admin

- members/views.py
Speed up the statistics page by reducing database load
> keep cached list of MembershipFees to reduce load on database

- members/models.py
- templates/members/member_list_superuser.inc
> add monthly fee to member list

- templates/base.html
Mit HETTI, Mitgliederliste und Announce verlinkt
> more links for superusers

- members/fixtures/default_choices.json
Add fitting fee_category and spind values to KindOfMembership fixtures
> update fixtures to include fee_category and spind values

- announce/views.py
- members/admin.py
- members/models.py
- mos/settings/common.py
- templates/members/new_member_welcome.mail
- templates/members/new_member_welcome.mail.subject
> Add button to send welcome mail to new members

- cal/admin.py
- cal/feeds.py
- cal/forms.py
- cal/migrations/0001_initial.py
- cal/urls.py
- cal/views.py
- core/migrations/0001_initial.py
- members/admin.py
- members/management/commands/domail.py
- members/management/commands/import_payment.py
- members/management/commands/import_payment_csv.py
- members/management/commands/list_intern_emails.py
- members/management/commands/member_categories.py
- members/migrations/0001_initial.py
- members/models.py
- members/urls.py
- projects/admin.py
- projects/migrations/0001_initial.py
- projects/models.py
- projects/urls.py
- sources/migrations/0001_initial.py
- sources/models.py
This is just code cleanup that yeets some cruft from python 2.7.
> chore: remove python27-isms (future imports, arguments to super)

- cal/urls.py
- cal/views.py
Lorem ipsum dolor sit amet, sus amogus venit impostoram
(See: #141 )
> Upcoming public events endpoint - implements #141

- templates/cal/eventinfo_detail.inc
> allow users to change the advertise when editing an event

- templates/members/new_member_welcome.mail
Formulierungen zu Passwort-Reset angepasst, Matrix-Raum ergänzt.
> Texte angepasst

- cal/models.py
to depict the advertise field into the calender object for the Event
PUBLIC -> Advertised Events
PRIVATE -> Other events
> feat(cal_export): added RFC5545#3.8.1.3 CLASS field to export

- members/models.py
- mos/settings/common.py
- requirements.txt
- templates/index.html
with misc thumbnail size adaption
x
adapted fix #79 and fixes #78 
another point on list done #152
> Added thumbnailer for member avatars

- mos/settings/common.py
Fixes #164, which was created as sub task to #66
> Fixes #164

- templates/members/members_details.inc
> add link to django-admin to member page for superusers

- members/models.py
Validates the entered IBAN of a member in the admin interface, resolves #173
> Validator for IBANs

- cal/views.py
- static/stylesheets/cal.css
> Implement location display in calendar view

- cal/views.py
compute start and end day in advance to improve readability
> refactor: feat(views.py): implemented better date presentation for multi day

- cal/forms.py
- cal/tests.py
> 201 calendar negative durations

- cal/forms.py
> remove wiki root from wiki url if it's added fixes #203

- cal/forms.py
> check if wikipage exists and disallow user pages for public events

- members/admin.py
added export members with monthly and outstanding fees as csv as an admin action in the users view.
closes #259
> export members with fees as CSV 

- members/templates/admin/change_form.html
- mos/settings/common.py
- static/javascripts/formset_handler.js
> make admin sections collapsable

- cal/forms.py
> Added collision Check

- cal/forms.py
events don't get physically deleted so we need to check the delete flag to exclude them from collision detection
> exclude deleted events from collisions
